---
title: "RWorksheet 1"
author: "Agatha Hazel Narra"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r}
#1. set up a vector named age, consisting of:
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51, 35, 24, 33, 41)

#a. how many data points?
num_data_points <- length(age)

#output
num_data_points
```

```{r}
#2. Find the reciprocal of the age value
reciprocal_age <- 1 / age

#output
reciprocal_age
```

```{r}
#3. Assign also new_age 
new_age <- c(age, 0, age)

#output
new_age
```

```{r}
#4. sort the values for age
sorted_age <- sort(age)

#output
sorted_age
```

```{r}
#5. find the minimum and maximum value for age.
maximum_age <- max(age)
minimum_age <- min(age)

#output
maximum_age
minimum_age
```
```{r}
#6. set up a vector named data, consisting of:
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5, 2.3, 2.5, 2.3, 2.4, 2.7)
num_data_pointsb <- length(data)

#output
num_data_pointsb
```
```{r}
#7. generate a new vector for data where double every value of data.
doubled_data <- data * 2

#output
doubled_data
```
```{r}
#8.1
sequence_1_to_100 <- seq(1:100)

#8.2
numsequence_20_to_60 <- 20:60

#8.3
mean_20_to_60 <- mean(numsequence_20_to_60)

#8.4
sum_51_to_91 <- sum(51:91)

#8.5
integers_1_to_1000 <- 1:1000

#output
integers_1_to_1000

#a.
total_datapoints <- length(sequence_1_to_100) + length(numsequence_20_to_60) + length(numsequence_20_to_60) + length(51:91)

#b.
#output
sequence_1_to_100
numsequence_20_to_60
mean_20_to_60
total_datapoints

#c. 
max_integers_1_to_1000 <- max(integers_1_to_1000)
```
```{r}
#9
numbers <- seq(1:100)
filtered_numbers <- Filter(function(i) { all(i %% c(3,5,7) != 0) }, seq(100))

print(filtered_numbers)
```
```{r}
# 10. Generate a sequence from 1 to 100
seq_1_to_100 <- 1:100

# Reverse sequence
seq_100_to_1 <- rev(seq_1_to_100)

# result
seq_100_to_1 
```
```{r}
# 11. list all the natural numbers below 25 that are multiples of 3 or 5
nums_bellow_25 <- 1:24

# find numbers that are multiples of 3 or 5
multiples_of_3_or_5 <- numbers[numbers %% 3 == 0 | numbers %% 5 == 0]

# Sum of multiples
sum_multiples <- sum(multiples_of_3_or_5)

# results
multiples_of_3_or_5
sum_multiples
```
```{r, error = TRUE}
# 12
x <- {0 + x + 5 + }

# The message indicates that R encountered an unexpected end of input because the expression is not complete. R is expecting more input to finish the statement.
```
```{r}
# 13. Set up the vector
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75, 77)

x2 <- score[2]
x3 <- score[3]


print (x2)
print (x3)
```
```{r}
# 14. 
# Create the vector
a <- c(1, 2, NA, 4, NA, 6, 7)

# Print the vector with NA values displayed as -999
print(a, na.print = "-999")

#output 
#  1   2 -999    4 -999    6    7 
#Original Vector: a is c(1, 2, NA, 4, NA, 6, 7). Printing with na.print: NA values are displayed as -999 in the output. The actual vector a stays the same; only how it’s printed is affected.
```
```{r}
# 15 
#Prompt for name and age

name = readline(prompt="Input your name: ")

age = readline(prompt="Input your age: ")

print(paste("My name is", name, "and I am", age, "years old."))
```
